// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package main

import (
	"time"
)

type AccountInput struct {
	Name string `json:"name"`
}

type AccountUpdateInput struct {
	ID   string  `json:"id"`
	Name *string `json:"name,omitempty"`
}

type Mutation struct {
}

type Order struct {
	ID         string             `json:"id"`
	CreatedAt  time.Time          `json:"created_at"`
	UpdatedAt  time.Time          `json:"updated_at"`
	TotalPrice float64            `json:"totalPrice"`
	Products   []*OrderedProducts `json:"products"`
}

type OrderInput struct {
	AccountID string               `json:"accountId"`
	Products  []*OrderProductInput `json:"products"`
}

type OrderProductInput struct {
	ID       string `json:"id"`
	Quantity int    `json:"quantity"`
}

type OrderedProducts struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Price     float64   `json:"price"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Quantity  int       `json:"quantity"`
}

type PaginationInput struct {
	Skip *int `json:"skip,omitempty"`
	Take *int `json:"take,omitempty"`
}

type Product struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Price     float64   `json:"price"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ProductInput struct {
	Name  string  `json:"name"`
	Price float64 `json:"price"`
}

type ProductUpdateInput struct {
	ID    string   `json:"id"`
	Price *float64 `json:"price,omitempty"`
	Name  *string  `json:"name,omitempty"`
}

type Query struct {
}
